#pragma once
#include "Base/PrimitiveTypes.h"
#include "Base/BindingMacros.h"

ARISEN_BIND_PACKAGE("com.arisen.rhi.core")
ARISEN_BIND_MODULE("Core.RHI.dll")
ARISEN_BIND_NAMESPACE("Arisen.Native.RHI")

ARISEN_BIND_STRUCT(RHICapabilities)

typedef struct RHICapabilities
{
    int rayTracingSupported;
    int supportsDynamicRendering;

    ArisenEngine::UInt32 maxImageDimension1D;
    ArisenEngine::UInt32 maxImageDimension2D;
    ArisenEngine::UInt32 maxImageDimension3D;
    ArisenEngine::UInt32 maxImageDimensionCube;
    ArisenEngine::UInt32 maxImageArrayLayers;
    ArisenEngine::UInt32 maxTexelBufferElements;
    ArisenEngine::UInt32 maxUniformBufferRange;
    ArisenEngine::UInt32 maxStorageBufferRange;
    ArisenEngine::UInt32 maxPushConstantsSize;
    ArisenEngine::UInt32 maxMemoryAllocationCount;
    ArisenEngine::UInt32 maxSamplerAllocationCount;
    ArisenEngine::UInt64 bufferImageGranularity;
    ArisenEngine::UInt64 sparseAddressSpaceSize;
    ArisenEngine::UInt32 maxBoundDescriptorSets;
    ArisenEngine::UInt32 maxPerStageDescriptorSamplers;
    ArisenEngine::UInt32 maxPerStageDescriptorUniformBuffers;
    ArisenEngine::UInt32 maxPerStageDescriptorStorageBuffers;
    ArisenEngine::UInt32 maxPerStageDescriptorSampledImages;
    ArisenEngine::UInt32 maxPerStageDescriptorStorageImages;
    ArisenEngine::UInt32 maxPerStageDescriptorInputAttachments;
    ArisenEngine::UInt32 maxPerStageResources;
    ArisenEngine::UInt32 maxDescriptorSetSamplers;
    ArisenEngine::UInt32 maxDescriptorSetUniformBuffers;
    ArisenEngine::UInt32 maxDescriptorSetUniformBuffersDynamic;
    ArisenEngine::UInt32 maxDescriptorSetStorageBuffers;
    ArisenEngine::UInt32 maxDescriptorSetStorageBuffersDynamic;
    ArisenEngine::UInt32 maxDescriptorSetSampledImages;
    ArisenEngine::UInt32 maxDescriptorSetStorageImages;
    ArisenEngine::UInt32 maxDescriptorSetInputAttachments;
    ArisenEngine::UInt32 maxVertexInputAttributes;
    ArisenEngine::UInt32 maxVertexInputBindings;
    ArisenEngine::UInt32 maxVertexInputAttributeOffset;
    ArisenEngine::UInt32 maxVertexInputBindingStride;
    ArisenEngine::UInt32 maxVertexOutputComponents;
    ArisenEngine::UInt32 maxTessellationGenerationLevel;
    ArisenEngine::UInt32 maxTessellationPatchSize;
    ArisenEngine::UInt32 maxTessellationControlPerVertexInputComponents;
    ArisenEngine::UInt32 maxTessellationControlPerVertexOutputComponents;
    ArisenEngine::UInt32 maxTessellationControlPerPatchOutputComponents;
    ArisenEngine::UInt32 maxTessellationControlTotalOutputComponents;
    ArisenEngine::UInt32 maxTessellationEvaluationInputComponents;
    ArisenEngine::UInt32 maxTessellationEvaluationOutputComponents;
    ArisenEngine::UInt32 maxGeometryShaderInvocations;
    ArisenEngine::UInt32 maxGeometryInputComponents;
    ArisenEngine::UInt32 maxGeometryOutputComponents;
    ArisenEngine::UInt32 maxGeometryOutputVertices;
    ArisenEngine::UInt32 maxGeometryTotalOutputComponents;
    ArisenEngine::UInt32 maxFragmentInputComponents;
    ArisenEngine::UInt32 maxFragmentOutputAttachments;
    ArisenEngine::UInt32 maxFragmentDualSrcAttachments;
    ArisenEngine::UInt32 maxFragmentCombinedOutputResources;
    ArisenEngine::UInt32 maxComputeSharedMemorySize;
    ArisenEngine::UInt32 maxComputeWorkGroupCountX;
    ArisenEngine::UInt32 maxComputeWorkGroupCountY;
    ArisenEngine::UInt32 maxComputeWorkGroupCountZ;
    ArisenEngine::UInt32 maxComputeWorkGroupInvocations;
    ArisenEngine::UInt32 maxComputeWorkGroupSizeX;
    ArisenEngine::UInt32 maxComputeWorkGroupSizeY;
    ArisenEngine::UInt32 maxComputeWorkGroupSizeZ;
    ArisenEngine::UInt32 subPixelPrecisionBits;
    ArisenEngine::UInt32 subTexelPrecisionBits;
    ArisenEngine::UInt32 mipmapPrecisionBits;
    ArisenEngine::UInt32 maxDrawIndexedIndexValue;
    ArisenEngine::UInt32 maxDrawIndirectCount;
    ArisenEngine::Float32 maxSamplerLodBias;
    ArisenEngine::Float32 maxSamplerAnisotropy;
    ArisenEngine::UInt32 maxViewports;
    ArisenEngine::UInt32 maxViewportDimensionsX;
    ArisenEngine::UInt32 maxViewportDimensionsY;
    ArisenEngine::Float32 viewportBoundsRangeMin;
    ArisenEngine::Float32 viewportBoundsRangeMax;
    ArisenEngine::UInt32 viewportSubPixelBits;
    ArisenEngine::UInt64 minMemoryMapAlignment;
    ArisenEngine::UInt64 minTexelBufferOffsetAlignment;
    ArisenEngine::UInt64 minUniformBufferOffsetAlignment;
    ArisenEngine::UInt64 minStorageBufferOffsetAlignment;
    ArisenEngine::SInt32 minTexelOffset;
    ArisenEngine::UInt32 maxTexelOffset;
    ArisenEngine::SInt32 minTexelGatherOffset;
    ArisenEngine::UInt32 maxTexelGatherOffset;
    ArisenEngine::Float32 minInterpolationOffset;
    ArisenEngine::Float32 maxInterpolationOffset;
    ArisenEngine::UInt32 subPixelInterpolationOffsetBits;
    ArisenEngine::UInt32 maxFramebufferWidth;
    ArisenEngine::UInt32 maxFramebufferHeight;
    ArisenEngine::UInt32 maxFramebufferLayers;
    ArisenEngine::UInt32 framebufferColorSampleCounts;
    ArisenEngine::UInt32 framebufferDepthSampleCounts;
    ArisenEngine::UInt32 framebufferStencilSampleCounts;
    ArisenEngine::UInt32 framebufferNoAttachmentsSampleCounts;
    ArisenEngine::UInt32 maxColorAttachments;
    ArisenEngine::UInt32 sampledImageColorSampleCounts;
    ArisenEngine::UInt32 sampledImageIntegerSampleCounts;
    ArisenEngine::UInt32 sampledImageDepthSampleCounts;
    ArisenEngine::UInt32 sampledImageStencilSampleCounts;
    ArisenEngine::UInt32 storageImageSampleCounts;
    ArisenEngine::UInt32 maxSampleMaskWords;
    int timestampComputeAndGraphics;
    ArisenEngine::Float32 timestampPeriod;
    ArisenEngine::UInt32 maxClipDistances;
    ArisenEngine::UInt32 maxCullDistances;
    ArisenEngine::UInt32 maxCombinedClipAndCullDistances;
    ArisenEngine::UInt32 discreteQueuePriorities;
    ArisenEngine::Float32 pointSizeRangeMin;
    ArisenEngine::Float32 pointSizeRangeMax;
    ArisenEngine::Float32 lineWidthRangeMin;
    ArisenEngine::Float32 lineWidthRangeMax;
    ArisenEngine::Float32 pointSizeGranularity;
    ArisenEngine::Float32 lineWidthGranularity;
    int strictLines;
    int standardSampleLocations;
    ArisenEngine::UInt64 optimalBufferCopyOffsetAlignment;
    ArisenEngine::UInt64 optimalBufferCopyRowPitchAlignment;
    ArisenEngine::UInt64 nonCoherentAtomSize;
    int supportDescriptorBuffer;
} RHICapabilities;

