#pragma once
#include "Base/BindingMacros.h"

ARISEN_BIND_PACKAGE("com.arisen.rhi.core")
ARISEN_BIND_MODULE("Core.RHI.dll")
ARISEN_BIND_NAMESPACE("Arisen.Native.RHI")

namespace ArisenEngine::RHI
{
    ARISEN_BIND_ENUM(EBlendFactor)

    typedef enum EBlendFactor
    {
        BLEND_FACTOR_ZERO = 0,
        BLEND_FACTOR_ONE = 1,
        BLEND_FACTOR_SRC_COLOR = 2,
        BLEND_FACTOR_ONE_MINUS_SRC_COLOR = 3,
        BLEND_FACTOR_DST_COLOR = 4,
        BLEND_FACTOR_ONE_MINUS_DST_COLOR = 5,
        BLEND_FACTOR_SRC_ALPHA = 6,
        BLEND_FACTOR_ONE_MINUS_SRC_ALPHA = 7,
        BLEND_FACTOR_DST_ALPHA = 8,
        BLEND_FACTOR_ONE_MINUS_DST_ALPHA = 9,
        BLEND_FACTOR_CONSTANT_COLOR = 10,
        BLEND_FACTOR_ONE_MINUS_CONSTANT_COLOR = 11,
        BLEND_FACTOR_CONSTANT_ALPHA = 12,
        BLEND_FACTOR_ONE_MINUS_CONSTANT_ALPHA = 13,
        BLEND_FACTOR_SRC_ALPHA_SATURATE = 14,
        BLEND_FACTOR_SRC1_COLOR = 15,
        BLEND_FACTOR_ONE_MINUS_SRC1_COLOR = 16,
        BLEND_FACTOR_SRC1_ALPHA = 17,
        BLEND_FACTOR_ONE_MINUS_SRC1_ALPHA = 18,
        BLEND_FACTOR_MAX_ENUM = 0x7FFFFFFF
    } EBlendFactor;
}

