#pragma once

#include "Base/BindingMacros.h"

ARISEN_BIND_PACKAGE("com.arisen.rhi.core")
ARISEN_BIND_MODULE("Core.RHI.dll")
ARISEN_BIND_NAMESPACE("Arisen.Native.RHI")

namespace ArisenEngine::RHI
{
    ARISEN_BIND_ENUM(EPipelineBindPoint)

    typedef enum EPipelineBindPoint
    {
        PIPELINE_BIND_POINT_GRAPHICS = 0,
        PIPELINE_BIND_POINT_COMPUTE = 1,
#ifdef VK_ENABLE_BETA_EXTENSIONS
        PIPELINE_BIND_POINT_EXECUTION_GRAPH_AMDX = 1000134000,
#endif
        PIPELINE_BIND_POINT_RAY_TRACING_KHR = 1000165000,
        PIPELINE_BIND_POINT_SUBPASS_SHADING_HUAWEI = 1000369003,
        PIPELINE_BIND_POINT_RAY_TRACING_NV = PIPELINE_BIND_POINT_RAY_TRACING_KHR,
        PIPELINE_BIND_POINT_MAX_ENUM = 0x7FFFFFFF
    } EPipelineBindPoint;
}

