#pragma once
#include "Base/BindingMacros.h"

ARISEN_BIND_PACKAGE("com.arisen.rhi.core")
ARISEN_BIND_MODULE("Core.RHI.dll")
ARISEN_BIND_NAMESPACE("Arisen.Native.RHI")

namespace ArisenEngine::RHI
{
    ARISEN_BIND_ENUM(EShaderStage)

    // VkShaderStageFlagBits
    typedef enum EShaderStage
    {
        SHADER_STAGE_VERTEX_BIT = 0x00000001,
        SHADER_STAGE_TESSELLATION_CONTROL_BIT = 0x00000002,
        SHADER_STAGE_TESSELLATION_EVALUATION_BIT = 0x00000004,
        SHADER_STAGE_GEOMETRY_BIT = 0x00000008,
        SHADER_STAGE_FRAGMENT_BIT = 0x00000010,
        SHADER_STAGE_COMPUTE_BIT = 0x00000020,
        SHADER_STAGE_ALL_GRAPHICS = 0x0000001F,
        SHADER_STAGE_ALL = 0x7FFFFFFF,
        SHADER_STAGE_RAYGEN_BIT = 0x00000100,
        SHADER_STAGE_ANY_HIT_BIT = 0x00000200,
        SHADER_STAGE_CLOSEST_HIT_BIT = 0x00000400,
        SHADER_STAGE_MISS_BIT = 0x00000800,
        SHADER_STAGE_INTERSECTION_BIT = 0x00001000,
        SHADER_STAGE_CALLABLE_BIT = 0x00002000,
        SHADER_STAGE_TASK_BIT_EXT = 0x00000040,
        SHADER_STAGE_MESH_BIT_EXT = 0x00000080,
        SHADER_STAGE_SUBPASS_SHADING_BIT_HUAWEI = 0x00004000,
        SHADER_STAGE_CLUSTER_CULLING_BIT_HUAWEI = 0x00080000,
        SHADER_STAGE_RAYGEN_BIT_NV = SHADER_STAGE_RAYGEN_BIT,
        SHADER_STAGE_ANY_HIT_BIT_NV = SHADER_STAGE_ANY_HIT_BIT,
        SHADER_STAGE_CLOSEST_HIT_BIT_NV = SHADER_STAGE_CLOSEST_HIT_BIT,
        SHADER_STAGE_MISS_BIT_NV = SHADER_STAGE_MISS_BIT,
        SHADER_STAGE_INTERSECTION_BIT_NV = SHADER_STAGE_INTERSECTION_BIT,
        SHADER_STAGE_CALLABLE_BIT_NV = SHADER_STAGE_CALLABLE_BIT,
        SHADER_STAGE_TASK_BIT_NV = SHADER_STAGE_TASK_BIT_EXT,
        SHADER_STAGE_MESH_BIT_NV = SHADER_STAGE_MESH_BIT_EXT,
        SHADER_STAGE_MAX_ENUM = 0x7FFFFFFF
    } EShaderStage;
}

