#pragma once
#include "Base/BindingMacros.h"

ARISEN_BIND_PACKAGE("com.arisen.rhi.core")
ARISEN_BIND_MODULE("Core.RHI.dll")
ARISEN_BIND_NAMESPACE("Arisen.Native.RHI")

namespace ArisenEngine::RHI
{
    ARISEN_BIND_ENUM(EBufferCreateFlagBits)

    typedef enum EBufferCreateFlagBits
    {
        BUFFER_CREATE_SPARSE_BINDING_BIT = 0x00000001,
        BUFFER_CREATE_SPARSE_RESIDENCY_BIT = 0x00000002,
        BUFFER_CREATE_SPARSE_ALIASED_BIT = 0x00000004,
        BUFFER_CREATE_PROTECTED_BIT = 0x00000008,
        BUFFER_CREATE_DEVICE_ADDRESS_CAPTURE_REPLAY_BIT = 0x00000010,
        BUFFER_CREATE_DESCRIPTOR_BUFFER_CAPTURE_REPLAY_BIT_EXT = 0x00000020,
        BUFFER_CREATE_VIDEO_PROFILE_INDEPENDENT_BIT_KHR = 0x00000040,
        BUFFER_CREATE_DEVICE_ADDRESS_CAPTURE_REPLAY_BIT_EXT = BUFFER_CREATE_DEVICE_ADDRESS_CAPTURE_REPLAY_BIT,
        BUFFER_CREATE_DEVICE_ADDRESS_CAPTURE_REPLAY_BIT_KHR = BUFFER_CREATE_DEVICE_ADDRESS_CAPTURE_REPLAY_BIT,
        BUFFER_CREATE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
    } EBufferCreateFlagBits;
}

