#pragma once
#include "Base/BindingMacros.h"

ARISEN_BIND_PACKAGE("com.arisen.rhi.core")
ARISEN_BIND_MODULE("Core.RHI.dll")
ARISEN_BIND_NAMESPACE("Arisen.Native.RHI")

namespace ArisenEngine::RHI
{
    ARISEN_BIND_ENUM(EAttachmentStoreOp)

    typedef enum EAttachmentStoreOp
    {
        ATTACHMENT_STORE_OP_STORE = 0,
        ATTACHMENT_STORE_OP_DONT_CARE = 1,
        ATTACHMENT_STORE_OP_NONE = 1000301000,
        ATTACHMENT_STORE_OP_NONE_KHR = ATTACHMENT_STORE_OP_NONE,
        ATTACHMENT_STORE_OP_NONE_QCOM = ATTACHMENT_STORE_OP_NONE,
        ATTACHMENT_STORE_OP_NONE_EXT = ATTACHMENT_STORE_OP_NONE,
        ATTACHMENT_STORE_OP_MAX_ENUM = 0x7FFFFFFF
    } EAttachmentStoreOp;
}

