#pragma once
#include "Base/BindingMacros.h"

ARISEN_BIND_PACKAGE("com.arisen.rhi.core")
ARISEN_BIND_MODULE("Core.RHI.dll")
ARISEN_BIND_NAMESPACE("Arisen.Native.RHI")

namespace ArisenEngine::RHI
{
    ARISEN_BIND_ENUM(EBorderColor)

    typedef enum EBorderColor
    {
        BORDER_COLOR_FLOAT_TRANSPARENT_BLACK = 0,
        BORDER_COLOR_INT_TRANSPARENT_BLACK = 1,
        BORDER_COLOR_FLOAT_OPAQUE_BLACK = 2,
        BORDER_COLOR_INT_OPAQUE_BLACK = 3,
        BORDER_COLOR_FLOAT_OPAQUE_WHITE = 4,
        BORDER_COLOR_INT_OPAQUE_WHITE = 5,
        BORDER_COLOR_FLOAT_CUSTOM_EXT = 1000287003,
        BORDER_COLOR_INT_CUSTOM_EXT = 1000287004,
        BORDER_COLOR_MAX_ENUM = 0x7FFFFFFF
    } EBorderColor;
}

