#pragma once
#include "Base/BindingMacros.h"

ARISEN_BIND_PACKAGE("com.arisen.rhi.core")
ARISEN_BIND_MODULE("Core.RHI.dll")
ARISEN_BIND_NAMESPACE("Arisen.Native.RHI")

namespace ArisenEngine::RHI
{
    ARISEN_BIND_ENUM(EImageLayout)

    typedef enum EImageLayout
    {
        IMAGE_LAYOUT_UNDEFINED = 0,
        IMAGE_LAYOUT_GENERAL = 1,
        IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL = 2,
        IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL = 3,
        IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL = 4,
        IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL = 5,
        IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL = 6,
        IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL = 7,
        IMAGE_LAYOUT_PREINITIALIZED = 8,
        IMAGE_LAYOUT_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL = 1000117000,
        IMAGE_LAYOUT_DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL = 1000117001,
        IMAGE_LAYOUT_DEPTH_ATTACHMENT_OPTIMAL = 1000241000,
        IMAGE_LAYOUT_DEPTH_READ_ONLY_OPTIMAL = 1000241001,
        IMAGE_LAYOUT_STENCIL_ATTACHMENT_OPTIMAL = 1000241002,
        IMAGE_LAYOUT_STENCIL_READ_ONLY_OPTIMAL = 1000241003,
        IMAGE_LAYOUT_READ_ONLY_OPTIMAL = 1000314000,
        IMAGE_LAYOUT_ATTACHMENT_OPTIMAL = 1000314001,
        IMAGE_LAYOUT_PRESENT_SRC_KHR = 1000001002,
        IMAGE_LAYOUT_VIDEO_DECODE_DST_KHR = 1000024000,
        IMAGE_LAYOUT_VIDEO_DECODE_SRC_KHR = 1000024001,
        IMAGE_LAYOUT_VIDEO_DECODE_DPB_KHR = 1000024002,
        IMAGE_LAYOUT_SHARED_PRESENT_KHR = 1000111000,
        IMAGE_LAYOUT_FRAGMENT_DENSITY_MAP_OPTIMAL_EXT = 1000218000,
        IMAGE_LAYOUT_FRAGMENT_SHADING_RATE_ATTACHMENT_OPTIMAL_KHR = 1000164003,
#ifdef VK_ENABLE_BETA_EXTENSIONS
        IMAGE_LAYOUT_VIDEO_ENCODE_DST_KHR = 1000299000,
#endif
#ifdef VK_ENABLE_BETA_EXTENSIONS
        IMAGE_LAYOUT_VIDEO_ENCODE_SRC_KHR = 1000299001,
#endif
#ifdef VK_ENABLE_BETA_EXTENSIONS
        IMAGE_LAYOUT_VIDEO_ENCODE_DPB_KHR = 1000299002,
#endif
        IMAGE_LAYOUT_ATTACHMENT_FEEDBACK_LOOP_OPTIMAL_EXT = 1000339000,
        IMAGE_LAYOUT_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL_KHR =
        IMAGE_LAYOUT_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL,
        IMAGE_LAYOUT_DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL_KHR =
        IMAGE_LAYOUT_DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL,
        IMAGE_LAYOUT_SHADING_RATE_OPTIMAL_NV = IMAGE_LAYOUT_FRAGMENT_SHADING_RATE_ATTACHMENT_OPTIMAL_KHR,
        IMAGE_LAYOUT_DEPTH_ATTACHMENT_OPTIMAL_KHR = IMAGE_LAYOUT_DEPTH_ATTACHMENT_OPTIMAL,
        IMAGE_LAYOUT_DEPTH_READ_ONLY_OPTIMAL_KHR = IMAGE_LAYOUT_DEPTH_READ_ONLY_OPTIMAL,
        IMAGE_LAYOUT_STENCIL_ATTACHMENT_OPTIMAL_KHR = IMAGE_LAYOUT_STENCIL_ATTACHMENT_OPTIMAL,
        IMAGE_LAYOUT_STENCIL_READ_ONLY_OPTIMAL_KHR = IMAGE_LAYOUT_STENCIL_READ_ONLY_OPTIMAL,
        IMAGE_LAYOUT_READ_ONLY_OPTIMAL_KHR = IMAGE_LAYOUT_READ_ONLY_OPTIMAL,
        IMAGE_LAYOUT_ATTACHMENT_OPTIMAL_KHR = IMAGE_LAYOUT_ATTACHMENT_OPTIMAL,
        IMAGE_LAYOUT_MAX_ENUM = 0x7FFFFFFF
    } EImageLayout;
}

